#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  Web Upload Server — One-Command Installer
#  Supports: Ubuntu 20.04/22.04/24.04, Debian 11/12
#
#  Usage (from project directory):
#    bash install.sh
#
#  Or directly from GitHub:
#    bash <(curl -fsSL https://raw.githubusercontent.com/YOUR_USERNAME/YOUR_REPO/main/install.sh)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
step()    { echo -e "\n${BOLD}${BLUE}▶ $*${NC}"; }

# ── Config ────────────────────────────────────────────────────────────────────
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="web-upload"
NODE_MAJOR="20"          # LTS version

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "Please run as root or with sudo:\n  sudo bash install.sh"
fi

# ── OS check ──────────────────────────────────────────────────────────────────
if ! command -v apt-get &>/dev/null; then
    error "This installer supports Debian/Ubuntu only.\nFor other distros, follow the manual installation steps in README.md."
fi

echo -e "\n${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}   Web Upload Server — Automated Installer   ${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
info "App directory: $APP_DIR"

# ─────────────────────────────────────────────────────────────────────────────
step "1/7  Installing system dependencies"
# ─────────────────────────────────────────────────────────────────────────────
apt-get update -qq
apt-get install -y -qq curl gnupg ca-certificates lsb-release build-essential
success "System packages installed"

# ─────────────────────────────────────────────────────────────────────────────
step "2/7  Installing Node.js ${NODE_MAJOR} LTS"
# ─────────────────────────────────────────────────────────────────────────────
if node --version 2>/dev/null | grep -q "^v${NODE_MAJOR}"; then
    success "Node.js $(node --version) already installed"
else
    curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - -qq
    apt-get install -y -qq nodejs
    success "Node.js $(node --version) installed"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "3/7  Installing npm dependencies"
# ─────────────────────────────────────────────────────────────────────────────
cd "$APP_DIR"
npm install --omit=dev --silent
success "npm packages installed"

# ─────────────────────────────────────────────────────────────────────────────
step "4/7  Creating environment configuration"
# ─────────────────────────────────────────────────────────────────────────────
ENV_FILE="$APP_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists — skipping (delete it and re-run to regenerate)"
else
    # Generate a cryptographically random session secret
    SESSION_SECRET=$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")

    echo "Enter the port the app should listen on (default: 3000):"
    read -r -p "Port [3000]: " APP_PORT
    APP_PORT="${APP_PORT:-3000}"

    echo ""
    echo "Use PostgreSQL instead of SQLite? (leave blank for SQLite — recommended)"
    read -r -p "PostgreSQL URL [blank = SQLite]: " DB_URL

    cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date)
SESSION_SECRET=${SESSION_SECRET}
PORT=${APP_PORT}
EOF

    if [[ -n "$DB_URL" ]]; then
        echo "DATABASE_URL=${DB_URL}" >> "$ENV_FILE"
    fi

    chmod 600 "$ENV_FILE"
    success ".env created (permissions set to 600)"
fi

# Source .env so setup-admin can use PORT
set -a; source "$ENV_FILE"; set +a

# ─────────────────────────────────────────────────────────────────────────────
step "5/7  Creating upload directories"
# ─────────────────────────────────────────────────────────────────────────────
mkdir -p "$APP_DIR/uploads" "$APP_DIR/uploads_tmp"
success "Upload directories ready"

# ─────────────────────────────────────────────────────────────────────────────
step "6/7  Creating admin account"
# ─────────────────────────────────────────────────────────────────────────────
echo ""
DATABASE_URL="" node "$APP_DIR/setup-admin.js"

# ─────────────────────────────────────────────────────────────────────────────
step "7/7  Setting up systemd service"
# ─────────────────────────────────────────────────────────────────────────────
APP_PORT="${PORT:-3000}"
NODE_BIN="$(which node)"

cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Web Upload Server
After=network.target

[Service]
Type=simple
WorkingDirectory=${APP_DIR}
ExecStart=${NODE_BIN} server.js
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}
EnvironmentFile=${APP_DIR}/.env

# Security hardening
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}" --quiet
systemctl restart "${SERVICE_NAME}"
sleep 2

if systemctl is-active --quiet "${SERVICE_NAME}"; then
    success "Service '${SERVICE_NAME}' is running"
else
    warn "Service failed to start. Check logs: journalctl -u ${SERVICE_NAME} -n 50"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}   ✓  Installation Complete!                 ${NC}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  App running at:  ${CYAN}http://localhost:${APP_PORT}${NC}"
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo -e "    View logs:      journalctl -u ${SERVICE_NAME} -f"
echo -e "    Restart app:    systemctl restart ${SERVICE_NAME}"
echo -e "    Stop app:       systemctl stop ${SERVICE_NAME}"
echo ""
echo -e "  ${YELLOW}Next step (optional):${NC} Set up Nginx as a reverse proxy."
echo -e "  See README.md for the Nginx + SSL (Let's Encrypt) configuration."
echo ""
